import {
  CardSection,
  CardSectionBottomDescribe,
  CardSectionText,
  CardSectionTopTitle,
  CardSectionBottomPrice,
  CardSectionTop,
  CardSectionMiddle,
  CardSectionBottom,
  CardSectionBottomPercent,
  CardSectionMiddleSection,
  CardSectionMiddleSingleLineGraph,
  CardSectionMiddleGraphTextUnder,
  CardSectionMiddleGraph1,
  CardSectionMiddleGraph2,
  CardSectionMiddleGraph3,
  CardSectionMiddleGraph4,
  CardSectionMiddleGraph5,
  CardSectionMiddleGraph6,
  CardSectionMiddleGraph7,
} from "./Card.styled";

export const Card = () => {
  return (
    <CardSection>
      <CardSectionTop>
        <CardSectionText>
          <CardSectionTopTitle>Spending - Last 7 days</CardSectionTopTitle>
        </CardSectionText>
      </CardSectionTop>
      <CardSectionMiddle>
        <CardSectionMiddleSection>
          <CardSectionMiddleSingleLineGraph>
            <CardSectionMiddleGraph1></CardSectionMiddleGraph1>
            <CardSectionMiddleGraphTextUnder>
              mon
            </CardSectionMiddleGraphTextUnder>
          </CardSectionMiddleSingleLineGraph>
          <CardSectionMiddleSingleLineGraph>
            <CardSectionMiddleGraph2></CardSectionMiddleGraph2>
            <CardSectionMiddleGraphTextUnder>
              tue
            </CardSectionMiddleGraphTextUnder>
          </CardSectionMiddleSingleLineGraph>
          <CardSectionMiddleSingleLineGraph>
            <CardSectionMiddleGraph3></CardSectionMiddleGraph3>
            <CardSectionMiddleGraphTextUnder>
              wed
            </CardSectionMiddleGraphTextUnder>
          </CardSectionMiddleSingleLineGraph>
          <CardSectionMiddleSingleLineGraph>
            <CardSectionMiddleGraph4></CardSectionMiddleGraph4>
            <CardSectionMiddleGraphTextUnder>
              thu
            </CardSectionMiddleGraphTextUnder>
          </CardSectionMiddleSingleLineGraph>
          <CardSectionMiddleSingleLineGraph>
            <CardSectionMiddleGraph5></CardSectionMiddleGraph5>
            <CardSectionMiddleGraphTextUnder>
              fri
            </CardSectionMiddleGraphTextUnder>
          </CardSectionMiddleSingleLineGraph>
          <CardSectionMiddleSingleLineGraph>
            <CardSectionMiddleGraph6></CardSectionMiddleGraph6>
            <CardSectionMiddleGraphTextUnder>
              sat
            </CardSectionMiddleGraphTextUnder>
          </CardSectionMiddleSingleLineGraph>
          <CardSectionMiddleSingleLineGraph>
            <CardSectionMiddleGraph7></CardSectionMiddleGraph7>
            <CardSectionMiddleGraphTextUnder>
              sun
            </CardSectionMiddleGraphTextUnder>
          </CardSectionMiddleSingleLineGraph>
        </CardSectionMiddleSection>
      </CardSectionMiddle>
      <CardSectionBottom>
        <CardSectionText>
          <CardSectionBottomDescribe>
            Total this month
          </CardSectionBottomDescribe>
          <CardSectionBottomPrice>$478.33</CardSectionBottomPrice>
        </CardSectionText>
        <CardSectionText>
          <CardSectionBottomPercent>+2.4%</CardSectionBottomPercent>
          <CardSectionBottomDescribe>from last month</CardSectionBottomDescribe>
        </CardSectionText>
      </CardSectionBottom>
    </CardSection>
  );
};
